export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES'

export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS'

export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE'

export const INIT_SEARCH = 'INIT_SEARCH'